# -*- coding: utf-8 -*-
"""Automated_FIRMS_GEE_Wildfire_Assessment.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yMUiUi-3ZghTF3szWE2xkWmaEtyaINbp

# Automated_FIRMS_GEE_Wildfire_Assessment
**Linghan Qi**

**Last updated** 07/16/2026

## Project Overview
This notebook provides an automated, end-to-end spatial data pipeline for wildfire damage assessment and ecological recovery monitoring. By integrating **NASA FIRMS** active fire data with **Google Earth Engine (GEE)** cloud computing, this tool dynamically delineates fire perimeters, quantifies burn severity, and models long-term vegetation recovery trajectories.

## Key Features & Methodology
1. **Automated Data Ingestion:** Connects to the NASA FIRMS API to extract historical active fire anomalies (VIIRS/MODIS) within user-defined spatiotemporal parameters.
2. **Burn Severity Mapping (dNBR):** Computes the differenced Normalized Burn Ratio using Sentinel-2 L2A high-resolution multispectral imagery. Evaluates severity based on the official **USGS FIREMON** reclassification standards.
3. **Advanced Spatial Masking:** Implements a strict dual-masking algorithm utilizing the USDOS Global LSIB (ocean masking) and JRC Global Surface Water dataset (inland water masking) to eliminate false-positive atmospheric and glint artifacts.
4. **Time-Series Recovery Trajectory:** Extracts 12-month post-fire Normalized Difference Vegetation Index (NDVI) exclusively within the burned perimeter to statistically quantify ecological resilience against pre-fire baselines.
5. **Interactive Visualization:** Renders dynamic, multi-layered spatial maps using `geemap`, featuring academic legends and interactive thresholding.

## How to Use
1. Run the **Environment Setup** cell to install dependencies (`geemap`, `geopandas`).
2. Follow the prompt in the authentication cell to grant Google Earth Engine access.
3. Modify the parameters in the **Configuration Panel** (BBOX, Dates) below to run the analysis for any specific wildfire event globally.

# Parameters for all following tasks
"""

import os

# Do not commit API keys to source control. Set FIRMS_MAP_KEY in the environment
# before running the FIRMS download section. The GEE analysis can run without it.
MAP_KEY = os.getenv('FIRMS_MAP_KEY', '')
SOURCE = 'VIIRS_SNPP_SP'            # Can not use _NRT for historical data
# DAY_RANGE = '1'
START_DATE = '2025-01-07'
END_DATE = '2025-01-15'
BBOX = '-119.2,33.7,-117.8,34.5'

"""## Skip to **Calculate dNBR and display on map** if you don't want to download FIRMS data

Use the FIRMS API to fetch active fire data or historical fire data from NASA, save it as a CSV file or GeoDataFrame shapefile, and gracefully handle potential errors.
"""

import requests
import pandas as pd
import geopandas as gpd
import io
import time
from datetime import datetime, timedelta
import folium

"""## Fetch historical fire data from NASA FIRMS API in batches for a specified date range."""

def fetch_historical_firms_data(map_key, source, bbox, start_date_str, end_date_str):
    # Convert string dates to datetime objects for calculation
    start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
    end_date = datetime.strptime(end_date_str, "%Y-%m-%d")

    if start_date > end_date:
        print("❌ Error: Start date cannot be later than end date!")
        return None

    all_dataframes = []
    current_start = start_date

    current_time_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    print(f"[{current_time_str}] Starting to fetch historical data from {start_date_str} to {end_date_str}...")

    # Set maximum day range constraint (NASA limit for _SP is 5 days)
    MAX_DAY_RANGE = 5

    # Loop to slice dates, pushing forward by a maximum of 5 days each iteration
    while current_start <= end_date:
        # Calculate the DAY_RANGE needed for this batch (ensuring it doesn't exceed 5)
        days_diff = (end_date - current_start).days + 1
        day_range = min(MAX_DAY_RANGE, days_diff)

        # Format the current start date as a URL parameter
        date_param = current_start.strftime("%Y-%m-%d")

        url = f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/{map_key}/{source}/{bbox}/{day_range}/{date_param}"
        batch_end_date = (current_start + timedelta(days=day_range - 1)).strftime("%Y-%m-%d")
        print(f"⏳ Fetching data from {date_param} to {batch_end_date} (Span: {day_range} days)...")

        try:
            response = requests.get(url, timeout=30)
            response.raise_for_status()

            csv_data = io.StringIO(response.text)
            df = pd.read_csv(csv_data)

            if not df.empty:
                all_dataframes.append(df)
            else:
                print(f"⚠️ Warning: No fire points detected during this specific time frame.")

        except requests.exceptions.HTTPError as errh:
            print(f"❌ HTTP Error (If 429 Too Many Requests, rate limit was triggered): {errh}")
        except Exception as err:
            print(f"❌ An unexpected error occurred: {err}")

        # Push forward and update the start date for the next loop iteration
        current_start += timedelta(days=day_range)

        # Protect the API Key: pause for 2 seconds after each request to avoid being blocked by NASA
        time.sleep(2)

    # Merge all dataframes after the loop ends
    if all_dataframes:
        final_df = pd.concat(all_dataframes, ignore_index=True)
        # Remove duplicates based on latitude, longitude, and time to ensure data purity
        final_df = final_df.drop_duplicates(subset=['latitude', 'longitude', 'acq_date', 'acq_time'])
        print(f"🎉 Successfully completed! Fetched and merged {len(final_df)} historical fire records.")
        return final_df
    else:
        print("⚠️ No valid data obtained within the entire specified date range.")
        return None

"""## Fetch active fire data from NASA FIRMS API based on the provided parameters. Returns a Pandas DataFrame if successful, or None if an error occurs."""

def fetch_firms_data(map_key, source, day_range, bbox):
    url = f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/{map_key}/{source}/{bbox}/{day_range}"

    current_time_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    print(f"[{current_time_str}] Fetching data from NASA FIRMS...")

    try:
        # Send the network request with a 30-second timeout
        response = requests.get(url, timeout=30)
        # Raise an HTTPError if the status code is not 200
        response.raise_for_status()

        # Parse and inspect the data
        data = io.StringIO(response.text)
        df = pd.read_csv(data)

        # Check if active fire data was actually retrieved
        if df.empty:
            print("⚠️ WARNING: Request successful, but no active fires were detected in this area/timeframe.")
            return None

        print(f"🎉 Successfully retrieved {len(df)} active fire records from API.")
        return df

    except requests.exceptions.HTTPError as errh:
        print(f"❌ HTTP Error (Check API key or rate limits): {errh}")
    except requests.exceptions.ConnectionError as errc:
        print(f"❌ Connection Error: {errc}")
    except requests.exceptions.Timeout as errt:
        print(f"❌ Timeout Error: {errt}")
    except pd.errors.EmptyDataError:
        print("❌ Data Parsing Error: NASA returned invalid CSV format.")
    except Exception as err:
        print(f"❌ Unexpected error occurred during fetch: {err}")

    return None

"""## Save the provided DataFrame to a local CSV file. Only handles file I/O operations."""

def save_to_csv_files(df, base_filename):

    if df is None or df.empty:
        print("⚠️ No data to save.")
        return

    csv_name = f"{base_filename}.csv"

    try:
        # Save as CSV
        df.to_csv(csv_name, index=False, encoding='utf-8')
        print(f"✅ Saved CSV: {csv_name}")

    except Exception as e:
        print(f"❌ Error occurred while saving files: {e}")

"""## Save the provided DataFrame to a local Shapefile. Only handles file I/O operations."""

def save_to_shp_files(df, base_filename):
    if df is None or df.empty:
        print("⚠️ No data to save.")
        return

    shp_name = f"{base_filename}.shp"

    try:
        # Save as Shapefile
        gdf = gpd.GeoDataFrame(
            df,
            geometry=gpd.points_from_xy(df.longitude, df.latitude),
            crs="EPSG:4326"
        )
        gdf.to_file(shp_name, driver="ESRI Shapefile")
        print(f"✅ Saved Shapefile: {shp_name}")

    except Exception as e:
        print(f"❌ Error occurred while saving files: {e}")

"""## Retrieve data from FIRMS"""

# 2.1 Use the historical fetch function for date ranges. Skip this optional
# section when no key is configured instead of sending an invalid API request.
if MAP_KEY:
    fire_df = fetch_historical_firms_data(
          map_key=MAP_KEY,
          source=SOURCE,
          bbox=BBOX,
          start_date_str=START_DATE,
          end_date_str=END_DATE
    )
else:
    print("ℹ️ FIRMS download skipped. Set the FIRMS_MAP_KEY environment variable to enable it.")
    fire_df = None

"""## Generate shapefile & CSV file"""

# 3. If data was successfully fetched, save it to CSV and Shapefile
if fire_df is not None:
    file_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    # base_name = f"firms_data_{file_timestamp}"
    base_name = f"firms_data_historical_{START_DATE}_to_{END_DATE}_{file_timestamp}"
    save_to_csv_files(fire_df, base_name)
    save_to_shp_files(fire_df, base_name)

"""# Calculate dNBR and display on map"""

# Install these dependencies in a terminal before running this .py file:
# python -m pip install geemap ffmpeg-python

import ee                                                                       # Google Earth Engine API
import geemap                                                                   # interactive GEE maps
import folium                                                                   # interactive maps
import time                                                                     # time
import numpy as np                                                              # numerical arrays
import pandas as pd                                                             # data tables
import geopandas as gpd                                                         # geospatial dataframes
import matplotlib.pyplot as plt                                                 # plotting
import matplotlib.patches as mpatches                                           # legend patches
import matplotlib.colors as mcolors                                             # colour utilities
from matplotlib.gridspec import GridSpec                                        # subplot layout
from matplotlib.colors import LinearSegmentedColormap                           # custom colourmaps
from IPython.display import display, HTML                                       # notebook display
import ipywidgets as widgets                                                    # import widgets
from IPython.display import clear_output, display
import time
from datetime import datetime, timedelta

print("All libraries loaded!")                                                  # Confirm success

GEE_PROJECT_ID = os.getenv('GEE_PROJECT_ID', 'final-research-lq-gis')
try:
    ee.Initialize(project=GEE_PROJECT_ID)
except Exception:
    # Authenticate only when existing local credentials cannot initialize GEE.
    ee.Authenticate()
    ee.Initialize(project=GEE_PROJECT_ID)
print("GEE Authenticated successfully")                                          # Print Authentication Status

Map = geemap.Map()
roi = ee.Geometry.BBox(*[float(x) for x in BBOX.split(',')])
Map.centerObject(roi, 8)

# 1. Set time window based on FIRMS API dates
# Fire occurrence period: 30 days before fire start to 30 days after fire end
offset_days = 30
# Convert strings to datetime objects for calculations
start_dt = datetime.strptime(START_DATE, "%Y-%m-%d")
end_dt = datetime.strptime(END_DATE, "%Y-%m-%d")
if start_dt > end_dt:
    raise ValueError("START_DATE cannot be later than END_DATE")

# Earth Engine filterDate uses [start, end): the end date is exclusive.
prefire_start = (start_dt - timedelta(days=offset_days)).strftime("%Y-%m-%d")
prefire_end = START_DATE

postfire_start = (end_dt + timedelta(days=1)).strftime("%Y-%m-%d")
postfire_end = (end_dt + timedelta(days=offset_days + 1)).strftime("%Y-%m-%d")

# 2. Load Sentinel-2 Surface Reflectance (SR) dataset
s2 = ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")

def add_nbr(image):
    nbr = image.normalizedDifference(['B8', 'B12']).rename('NBR')
    return image.addBands(nbr)

def mask_s2_clouds(image):
    """Mask cloud, cirrus, cloud shadow, snow/ice, and invalid SCL pixels."""
    scl = image.select('SCL')
    invalid = (scl.eq(0)
               .Or(scl.eq(1))
               .Or(scl.eq(3))
               .Or(scl.eq(7))
               .Or(scl.eq(8))
               .Or(scl.eq(9))
               .Or(scl.eq(10))
               .Or(scl.eq(11)))
    return image.updateMask(invalid.Not())

def prepare_s2_collection(start_date_str, end_date_str):
    """Build a date-filtered collection with scene- and pixel-level cloud masks."""
    return (s2.filterBounds(roi)
            .filterDate(start_date_str, end_date_str)
            .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20))
            .map(mask_s2_clouds))

def get_median_composite(start_date_str, end_date_str, with_nbr=False,
                         allow_empty=False):
    """Return a median composite and source-image count for one time window."""
    collection = prepare_s2_collection(start_date_str, end_date_str)
    image_count = int(collection.size().getInfo())
    if image_count == 0:
        if allow_empty:
            return None, 0
        raise RuntimeError(
            f"No Sentinel-2 images found from {start_date_str} to "
            f"{end_date_str} with CLOUDY_PIXEL_PERCENTAGE < 20."
        )
    if with_nbr:
        collection = collection.map(add_nbr)
    return collection.median().clip(roi), image_count

def classify_dnbr(dnbr_image):
    """Classify continuous dNBR using USGS/FIREMON thresholds."""
    return (ee.Image(0)
            .where(dnbr_image.lt(-0.25), 1)
            .where(dnbr_image.gte(-0.25).And(dnbr_image.lt(-0.1)), 2)
            .where(dnbr_image.gte(-0.1).And(dnbr_image.lt(0.1)), 3)
            .where(dnbr_image.gte(0.1).And(dnbr_image.lt(0.27)), 4)
            .where(dnbr_image.gte(0.27).And(dnbr_image.lt(0.44)), 5)
            .where(dnbr_image.gte(0.44).And(dnbr_image.lt(0.66)), 6)
            .where(dnbr_image.gte(0.66), 7)
            .updateMask(dnbr_image.mask()))

print(f"⏳ Computing NBR median composite images for {prefire_start} to {prefire_end} and {postfire_start} to {postfire_end}")

# 3. Get pre-fire and post-fire images and calculate NBR.
# Fail early with a clear message if either baseline window has no source image.
pre_fire_img, pre_image_count = get_median_composite(
    prefire_start, prefire_end, with_nbr=True
)
post_fire_img, post_image_count = get_median_composite(
    postfire_start, postfire_end, with_nbr=True
)
print(f"✅ Source images: pre-fire={pre_image_count}, post-fire={post_image_count}")
# 4. Calculate dNBR for the last day
# dNBR = Pre-fire NBR - Post-fire NBR
dnbr = pre_fire_img.select('NBR').subtract(post_fire_img.select('NBR')).rename('dNBR')

# 5. Set dNBR visualization parameters
classified_dnbr = classify_dnbr(dnbr)

vis_dnbr = {
    'min': 1,
    'max': 7,
    'palette': [
        '006400', # 1: Dark Green (Significant recovery)
        '90EE90', # 2: Light Green (Slight recovery)
        'E0E0E0', # 3: Light Grey (Unburned)
        'FFFF00', # 4: Yellow (Low severity burn)
        'FFA500', # 5: Orange (Moderate-low severity burn)
        'FF0000', # 6: Red (Moderate-high severity burn)
        '800080'  # 7: Purple (High severity burn)
    ]
}

Map.addLayer(classified_dnbr, vis_dnbr, f'dNBR (Classified) - {START_DATE}')
Map

"""## Remove water & Ocean Masking"""

# ==========================================
# Remove deep ocean and inland water interference (Water & Ocean Masking)
# ==========================================

print("🌊 Applying land boundary and water mask, removing ocean and lake noise...")

# 1. Macro mask: Remove deep ocean (Ocean Masking)
# Retrieve the global simple land boundary vector dataset (LSIB) published by the U.S. Department of State
# This boundary is very clean and can completely shield the deep ocean
land_boundaries = ee.FeatureCollection("USDOS/LSIB_SIMPLE/2017")

# 2. Micro mask: Remove inland lakes and rivers (Inland Water Masking)
# Continue to use JRC data to delineate fine inland water bodies
jrc_water = ee.Image("JRC/GSW1_4/GlobalSurfaceWater")
inland_water_mask = jrc_water.select('max_extent').eq(0)

# 3. Apply spatial masks to the continuous dNBR image before classification.
dnbr_land = dnbr.clipToCollection(land_boundaries)
dnbr_clean = dnbr_land.updateMask(inland_water_mask)
dnbr_no_water = classify_dnbr(dnbr_clean)

# 5. Add the clean layer to the map
Map.addLayer(dnbr_no_water, vis_dnbr, f'dNBR (Cleaned) - {START_DATE}')

print("✅ Ocean and water noise completely cleared!")

"""## Add Legend on map if it does not have one"""

def add_unique_legend(map_obj, legend_dict, title, position, unique_tag):
    """
    Adds a legend to a geemap map, preventing duplicate additions.

    Parameters:
    map_obj: geemap.Map instance
    legend_dict: Dictionary containing text and colors
    title: Legend title
    position: Legend position on the map ('bottomright', 'bottomleft', etc.)
    unique_tag: Unique string tag to prevent duplication (e.g., 'dnbr_legend_added')
    """
    # Dynamically check if the map object already has this specific tag
    if not hasattr(map_obj, unique_tag):
        map_obj.add_legend(
            title=title,
            legend_dict=legend_dict,
            position=position
        )
        # Dynamically add the tag to the object with a value of True
        setattr(map_obj, unique_tag, True)
        print(f"✅ Legend 【{title}】 successfully loaded!")
    else:
        print(f"ℹ️ Legend 【{title}】 already exists, skipping duplicate addition.")

legend_dict_dnbr = {
    "Significant vegetation recovery (< -0.25)": "006400",
    "Slight vegetation recovery (-0.25 to -0.1)": "90EE90",
    "Unburned/No significant change (-0.1 to 0.1)": "E0E0E0",
    "Low severity burn (0.1 to 0.27)": "FFFF00",
    "Moderate-low severity burn (0.27 to 0.44)": "FFA500",
    "Moderate-high severity burn (0.44 to 0.66)": "FF0000",
    "High severity burn (> 0.66)": "800080"
}

add_unique_legend(
    map_obj=Map,
    legend_dict=legend_dict_dnbr,
    title="dNBR Burn Severity",
    position="bottomright",
    unique_tag="dnbr_legend"
)

print("✅ dNBR Legend loaded (duplicate protection enabled)!")
Map

"""## Fire Mask Thresholding"""

Map1 = geemap.Map()
Map1.centerObject(roi, 8)

print("🔥 Extracting burned areas with dNBR > 0.1...")

# ==========================================
# 1. Filtering step: Apply dNBR > 0.1 threshold (core step)
# ==========================================
# Use the continuous dNBR values, not the 1-7 class codes. The previous
# dnbr_no_water.gt(4) expression incorrectly removed class 4 (0.1-0.27).
burned_mask = dnbr_clean.gt(0.1)

# Use updateMask to make unburned areas with less than 0.1 transparent
burned_area_only = dnbr_no_water.updateMask(burned_mask)

# ==========================================
# 2. Optimize visualization parameters
# ==========================================
# Since we have filtered out healthy vegetation with dNBR < 0.1,
# we don't need green in the palette. Transition directly from yellow (low severity burn) to purple (high severity burn)
vis_burned_only = {
    'min': 4,
    'max': 7,
    'palette': ['ffff00', 'ffA500', 'ff0000', '800080'] # Yellow -> Orange -> Red -> Purple
}

# ==========================================
# 3. Load to map
# ==========================================
# Uncomment the following line if you haven't created Map before
# Map = geemap.Map(); Map.centerObject(roi, 7)

Map1.addLayer(burned_area_only, vis_burned_only, 'Burned Area Only (dNBR > 0.1)')

# ==========================================
# Add dNBR (Burn Severity) standard academic legend (duplicate protected)
# ==========================================

legend_dict_dnbr = {
    "Low severity burn (0.1 - 0.27)": "ffff00",
    "Moderate severity burn (0.27 - 0.44)": "ffA500",
    "Moderate-high severity burn (0.44 - 0.66)": "ff0000",
    "High severity burn (> 0.66)": "800080"
}

add_unique_legend(
    map_obj=Map1,
    legend_dict=legend_dict_dnbr,
    title="dNBR Burn Severity",
    position="bottomright",
    unique_tag="dnbr_legend"
)
print("✅ dNBR Legend loaded (duplicate protection enabled)!")

print("✅ Burned area layer generated! Unburned areas and water bodies are transparent.")
Map1

"""## Monthly dNBR change"""

Map2 = geemap.Map()
Map2.centerObject(roi, 8)

# Set the number of periods you want to track (e.g., track 12 months)
months_to_track = 12
window_days = 30 # Number of days per monitoring period

print("🌱 Starting post-fire vegetation recovery automated monitoring pipeline...")

for i in range(months_to_track):
    # Calculate the start and end time for the current assessment period
    # Round 1: Day 1 to Day 30 after the fire
    # Round 2: Day 31 to Day 60 after the fire... and so on
    period_start_dt = end_dt + timedelta(days=1 + i * window_days)
    period_end_exclusive_dt = period_start_dt + timedelta(days=window_days)
    period_end_inclusive_dt = period_end_exclusive_dt - timedelta(days=1)

    p_start_str = period_start_dt.strftime("%Y-%m-%d")
    p_end_str = period_end_exclusive_dt.strftime("%Y-%m-%d")

    print(
        f"Calculating recovery for post-fire month {i+1}: {p_start_str} to "
        f"{period_end_inclusive_dt.strftime('%Y-%m-%d')}"
    )

    recovery_img, recovery_count = get_median_composite(
        p_start_str, p_end_str, with_nbr=True, allow_empty=True
    )
    if recovery_img is None:
        print(f"⚠️ Month {i+1} skipped: no qualifying Sentinel-2 images.")
        continue

    # Add dNBR for each period to the map
    # dNBR = Fixed pre-fire image NBR - Current recovery period NBR
    # Note: pre_fire_img here is the median image for 30 days before the fire, calculated outside the loop
    recovery_dnbr = pre_fire_img.select('NBR').subtract(recovery_img.select('NBR')).rename(f'dNBR_Month_{i+1}')

    # Core modification: Apply dual water mask (clean noise)
    # First clip deep ocean with land boundaries, then updateMask with inland water mask
    # This ensures that only burned pixels on land and with dNBR > 0.1 are calculated and colored

    recovery_dnbr_clean = recovery_dnbr.clipToCollection(land_boundaries).updateMask(inland_water_mask).updateMask(burned_mask) # Only extract burn scar

    # Reclassification
    classified_recovery = classify_dnbr(recovery_dnbr_clean)

    # Dynamically add the spatial layer for this month to the map
    layer_name = (
        f"Post-Fire Month {i+1} dNBR "
        f"({p_start_str} to {period_end_inclusive_dt.strftime('%Y-%m-%d')})"
    )
    # By default, display the 1st month
    is_shown = True if i in [0] else False
    Map2.addLayer(classified_recovery, vis_dnbr, layer_name, is_shown)

print("✅ All recovery period layers loaded! Please switch and view them in the Layer Control on the top right of the map!")

# ==========================================
# Add dNBR (Burn Severity) standard academic legend (duplicate protected)
# ==========================================

legend_dict_dnbr_full = {
    "Significant vegetation recovery (< -0.25)": "006400",
    "Slight vegetation recovery (-0.25 to -0.1)": "90EE90",
    "Unburned/No significant change (-0.1 to 0.1)": "E0E0E0",
    "Low severity burn (0.1 to 0.27)": "FFFF00",
    "Moderate-low severity burn (0.27 to 0.44)": "FFA500",
    "Moderate-high severity burn (0.44 to 0.66)": "FF0000",
    "High severity burn (> 0.66)": "800080"
}

add_unique_legend(
    map_obj=Map2,
    legend_dict=legend_dict_dnbr_full,
    title="dNBR Burn Severity (USGS Full Version)",
    position="bottomright",
    unique_tag="dnbr_full_legend" # Updated duplicate protection tag name to ensure successful addition
)
print("✅ dNBR Legend loaded (duplicate protection enabled)!")

print("✅ dNBR Layer loaded!")
Map2

"""## Monthly NDVI change"""

Map3 = geemap.Map()
Map3.centerObject(roi, 8)

print("🗺️ Spatially clipping and rendering the post-fire burned area NDVI spatial evolution map for 12 months...")

# ==========================================
# 1. Define NDVI calculation function
# ==========================================
def get_ndvi(image):
    return image.normalizedDifference(['B8', 'B4']).rename('NDVI')

# ==========================================
# 2. Set classic NDVI gradient color band (USGS/NASA standard)
# From tan (burn scar/bare land) -> yellow (low vegetation/herbaceous) -> dark green (dense forest)
# ==========================================
vis_ndvi = {
    'min': 0.0,
    'max': 0.8,
    'palette': ['A52A2A', 'FFA500', 'FFFF00', '00FF00', '008000']
}

# ==========================================
# 3. Dynamically extract images for specific key months and apply dual masking
# ==========================================
# We select the 1st, 3rd, 6th, 9th, and 12th months after the disaster for spatial comparison
target_months = [1, 3, 6, 9, 12]

for m in target_months:
    # Calculate the time window for the current month
    start_date_dt = end_dt + timedelta(days=1 + (m - 1) * 30)
    end_date_exclusive_dt = start_date_dt + timedelta(days=30)
    end_date_inclusive_dt = end_date_exclusive_dt - timedelta(days=1)

    s_str = start_date_dt.strftime("%Y-%m-%d")
    e_str = end_date_exclusive_dt.strftime("%Y-%m-%d")

    # Extract median composite image for the current month
    monthly_img, monthly_count = get_median_composite(
        s_str, e_str, allow_empty=True
    )
    if monthly_img is None:
        print(f"⚠️ NDVI map month {m} skipped: no qualifying Sentinel-2 images.")
        continue

    # Calculate monthly land NDVI
    raw_ndvi = get_ndvi(monthly_img)

    # [Core Spatial Filtering]: Simultaneously update dual water mask and fire burned area mask (burned_mask)
    # This ensures that only burned pixels on land and with dNBR > 0.1 are calculated and colored
    clean_ndvi_burned_only = (raw_ndvi
                              .clipToCollection(land_boundaries) # Clip oceans
                              .updateMask(inland_water_mask)     # Mask out inland lakes
                              .updateMask(burned_mask))          # Only extract burn scar

    # Add the spatial layer for this month to the map
    layer_name = (
        f"Post-Fire Month {m} Burned Area NDVI "
        f"({s_str} to {end_date_inclusive_dt.strftime('%Y-%m-%d')})"
    )
    # By default, display the 1st month
    is_shown = True if m in [1] else False
    Map3.addLayer(clean_ndvi_burned_only, vis_ndvi, layer_name, is_shown)

# Add legend
legend_dict_ndvi = {
    "Water/Severe burn scar (< 0.0)": "A52A2A",
    "Bare land/Sparse herbaceous (0.0 - 0.2)": "FFA500",
    "Low density vegetation/Shrubs (0.2 - 0.4)": "FFFF00",
    "Medium density forest (0.4 - 0.6)": "00FF00",
    "High density healthy forest (> 0.6)": "008000"
}

add_unique_legend(
    map_obj=Map3,
    legend_dict=legend_dict_ndvi,
    title="NDVI Vegetation Recovery Index",
    position="bottomright",
    unique_tag="ndvi_legend"
)
print("✅ Burned area NDVI spatial time series layer loaded successfully!")

print("💡 Tip: You can use geemap's Split-panel tool on the map to directly drag left and right to compare the spatial differences between Month 1 (mainly red-yellow) and Month 12 (gradually turning green)!")
Map3

"""## NDVI change curve"""

import matplotlib.pyplot as plt

# ==========================================
# 1. Calculate pre-fire baseline NDVI for the burned area
# ==========================================
# pre_fire_img and burned_mask are variables already calculated in the previous code
pre_ndvi = get_ndvi(pre_fire_img)
pre_ndvi_burned_only = pre_ndvi.updateMask(burned_mask)

print("⏳ Calculating pre-fire NDVI baseline value...")
# Note: To prevent GEE timeout due to excessively large calculation areas, the scale parameter is set to 100m or 200m
pre_ndvi_val = pre_ndvi_burned_only.reduceRegion(
    reducer=ee.Reducer.mean(),
    geometry=roi,
    scale=100,
    maxPixels=1e10
).get('NDVI').getInfo()

if pre_ndvi_val is None:
    print("⚠️ No valid pre-fire NDVI baseline pixels were found in the burned area.")
else:
    print(f"🔥 Average pre-fire NDVI in the burned area: {pre_ndvi_val:.4f}")

# ==========================================
# 2. Loop to extract average NDVI for 12 months after the fire
# ==========================================
months_to_track = 12
dates = []
ndvi_values = []

print("📊 Extracting 12-month post-fire NDVI time series, cloud computing will take some time...")

for i in range(months_to_track):
    # Dynamically calculate the start and end dates for each month
    period_start_dt = end_dt + timedelta(days=1 + i * 30)
    period_end_exclusive_dt = period_start_dt + timedelta(days=30)
    period_end_inclusive_dt = period_end_exclusive_dt - timedelta(days=1)

    p_start_str = period_start_dt.strftime("%Y-%m-%d")
    p_end_str = period_end_exclusive_dt.strftime("%Y-%m-%d")

    # Retrieve median image for the current month
    monthly_img, monthly_count = get_median_composite(
        p_start_str, p_end_str, allow_empty=True
    )
    if monthly_img is None:
        print(f"⚠️ Month {i+1} skipped: no qualifying Sentinel-2 images.")
        continue

    # Calculate monthly NDVI and mask it with burned_mask, retaining only burned pixels
    monthly_ndvi = get_ndvi(monthly_img).updateMask(burned_mask)

    # Calculate the mean for this area
    try:
        mean_dict = monthly_ndvi.reduceRegion(
            reducer=ee.Reducer.mean(),
            geometry=roi,
            scale=100,
            maxPixels=1e10
        )
        val = mean_dict.get('NDVI').getInfo()

        if val is not None:
            dates.append(p_start_str)
            ndvi_values.append(val)
            print(
                f"✅ Month {i+1} ({p_start_str} to "
                f"{period_end_inclusive_dt.strftime('%Y-%m-%d')}): NDVI = {val:.4f}"
            )
        else:
            print(f"⚠️ Month {i+1} ({p_start_str}): No valid data (possibly fully cloud-covered this month)")
    except Exception as e:
        print(f"❌ Month {i+1} ({p_start_str}) extraction failed: {e}")

# ==========================================
# 3. Plot recovery trajectory line chart using Matplotlib
# ==========================================
if ndvi_values:
    df_ndvi = pd.DataFrame({'Date': pd.to_datetime(dates), 'NDVI': ndvi_values})

    # Set chart style
    plt.figure(figsize=(12, 6), dpi=100)

    # Plot monthly recovery curve
    plt.plot(df_ndvi['Date'], df_ndvi['NDVI'], marker='o', linestyle='-',
             color='forestgreen', linewidth=2.5, markersize=8, label='Post-fire NDVI Trajectory')

    # Draw pre-fire baseline
    if pre_ndvi_val is not None:
        plt.axhline(y=pre_ndvi_val, color='red', linestyle='--', linewidth=2,
                    label=f'Pre-fire Baseline ({pre_ndvi_val:.4f})')

    # Chart details beautification
    plt.title(f'Post-Fire Vegetation Recovery Trajectory (12 Months)', fontsize=16, fontweight='bold')
    plt.xlabel('Evaluation Date', fontsize=12)
    plt.ylabel('Mean NDVI within Burned Area', fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.legend(loc='lower right', fontsize=11)
    plt.xticks(rotation=45)
    plt.tight_layout()

    # Display output directly in Colab
    plt.show()
else:
    print("Not enough data collected to plot the chart.")
